create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 80),
  email text not null check (
    email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  ),
  message text not null check (char_length(trim(message)) between 10 and 2000),
  status text not null default 'new' check (
    status in ('new', 'read', 'replied', 'archived')
  ),
  created_at timestamptz not null default now()
);

create index if not exists contact_messages_created_at_idx
on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;

drop policy if exists "Public can submit contact messages" on public.contact_messages;

create policy "Public can submit contact messages"
on public.contact_messages
for insert
to anon
with check (
  char_length(trim(name)) between 2 and 80
  and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  and char_length(trim(message)) between 10 and 2000
);
